"""备份任务页面构建。"""

from __future__ import annotations

from PySide6.QtWidgets import QAbstractItemView, QCheckBox, QComboBox, QDoubleSpinBox, QFrame, QGridLayout, QHBoxLayout, QHeaderView, QLabel, QLineEdit, QPushButton, QTableWidget, QVBoxLayout, QWidget


class BackupPageMixin:
    """备份任务页面构建。"""

    def _build_backup_page(self) -> QWidget:
        backup_page = QWidget()
        backup_layout = QVBoxLayout(backup_page)
        backup_layout.setContentsMargins(24, 20, 24, 22)
        backup_layout.setSpacing(14)
        backup_layout.addWidget(QLabel("备份文件夹", objectName="title"))
        backup_note = QLabel(
            "定期扫描本地变动并上传。增量备份创建时间戳目录；同路径覆盖会更新远端文件，但不会删除远端多余文件。",
            objectName="subtitle",
        )
        backup_note.setWordWrap(True)
        backup_layout.addWidget(backup_note)
        self.backup_table = QTableWidget(0, 8)
        self.backup_table.setHorizontalHeaderLabels([
            "名称", "本地文件夹", "账户", "仓库", "目标目录", "模式", "周期", "状态"
        ])
        self.backup_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Interactive)
        self.backup_table.horizontalHeader().setStretchLastSection(True)
        self.backup_table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.backup_table.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self.backup_table.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.backup_table.setColumnWidth(0, 130)
        self.backup_table.setColumnWidth(1, 230)
        self.backup_table.setColumnWidth(2, 110)
        self.backup_table.setColumnWidth(3, 190)
        self.backup_table.itemSelectionChanged.connect(self._backup_selected)
        backup_layout.addWidget(self.backup_table, 1)

        backup_editor = QFrame(objectName="card")
        backup_editor_layout = QGridLayout(backup_editor)
        backup_editor_layout.setContentsMargins(18, 16, 18, 16)
        backup_editor_layout.setHorizontalSpacing(12)
        backup_editor_layout.setVerticalSpacing(10)
        backup_editor_layout.addWidget(QLabel("任务名称"), 0, 0)
        self.backup_name_edit = QLineEdit()
        self.backup_name_edit.setPlaceholderText("例如：项目保险箱")
        backup_editor_layout.addWidget(self.backup_name_edit, 0, 1)
        backup_editor_layout.addWidget(QLabel("本地文件夹"), 1, 0)
        local_row = QHBoxLayout()
        self.backup_local_edit = QLineEdit()
        self.backup_local_edit.setReadOnly(True)
        local_row.addWidget(self.backup_local_edit, 1)
        backup_browse = QPushButton("选择")
        backup_browse.clicked.connect(self._browse_backup_folder)
        local_row.addWidget(backup_browse)
        backup_editor_layout.addLayout(local_row, 1, 1, 1, 3)
        backup_editor_layout.addWidget(QLabel("账户"), 2, 0)
        self.backup_account_combo = QComboBox()
        self.backup_account_combo.currentIndexChanged.connect(self._render_backup_repository_options)
        backup_editor_layout.addWidget(self.backup_account_combo, 2, 1)
        backup_editor_layout.addWidget(QLabel("仓库"), 2, 2)
        self.backup_repo_combo = QComboBox()
        backup_editor_layout.addWidget(self.backup_repo_combo, 2, 3)
        backup_editor_layout.addWidget(QLabel("目标目录"), 3, 0)
        self.backup_dest_edit = QLineEdit()
        self.backup_dest_edit.setPlaceholderText("例如：backup/project")
        backup_editor_layout.addWidget(self.backup_dest_edit, 3, 1)
        backup_editor_layout.addWidget(QLabel("备份模式"), 3, 2)
        self.backup_mode_combo = QComboBox()
        self.backup_mode_combo.addItem("增量备份（时间戳）", "incremental")
        self.backup_mode_combo.addItem("同路径覆盖", "replace")
        backup_editor_layout.addWidget(self.backup_mode_combo, 3, 3)
        backup_editor_layout.addWidget(QLabel("扫描周期"), 4, 0)
        interval_row = QHBoxLayout()
        self.backup_interval_value = QDoubleSpinBox()
        self.backup_interval_value.setRange(0.1, 100000)
        self.backup_interval_value.setDecimals(1)
        self.backup_interval_value.setValue(30)
        interval_row.addWidget(self._stepper(self.backup_interval_value), 1)
        self.backup_interval_unit = QComboBox()
        self.backup_interval_unit.addItem("分钟", "minute")
        self.backup_interval_unit.addItem("小时", "hour")
        interval_row.addWidget(self.backup_interval_unit)
        backup_editor_layout.addLayout(interval_row, 4, 1)
        backup_editor_layout.addWidget(QLabel("云端同步阈值"), 4, 2)
        self.backup_download_limit = QDoubleSpinBox()
        self.backup_download_limit.setRange(0.01, 1024000)
        self.backup_download_limit.setDecimals(2)
        self.backup_download_limit.setValue(10)
        self.backup_download_limit.setSuffix(" MB 以下")
        backup_editor_layout.addWidget(self._stepper(self.backup_download_limit), 4, 3)
        self.backup_enabled = QCheckBox("启用定时备份")
        self.backup_enabled.setChecked(True)
        backup_editor_layout.addWidget(self.backup_enabled, 5, 1)
        backup_actions = QHBoxLayout()
        backup_new = QPushButton("新建")
        backup_new.clicked.connect(self._new_backup_job)
        backup_actions.addWidget(backup_new)
        backup_save = QPushButton("保存任务", objectName="primary")
        backup_save.clicked.connect(self._save_backup_job)
        backup_actions.addWidget(backup_save)
        backup_remove = QPushButton("移除")
        backup_remove.clicked.connect(self._remove_backup_job)
        backup_actions.addWidget(backup_remove)
        backup_actions.addStretch()
        self.backup_scan_button = QPushButton("立即扫描并上传")
        self.backup_scan_button.clicked.connect(self._scan_selected_backup)
        backup_actions.addWidget(self.backup_scan_button)
        self.backup_sync_button = QPushButton("从云端同步到本地")
        self.backup_sync_button.clicked.connect(self._sync_selected_backup)
        backup_actions.addWidget(self.backup_sync_button)
        backup_editor_layout.addLayout(backup_actions, 6, 0, 1, 4)
        self.backup_status_label = QLabel("尚未选择备份任务", objectName="subtitle")
        backup_editor_layout.addWidget(self.backup_status_label, 7, 0, 1, 4)
        backup_layout.addWidget(backup_editor)

        return backup_page
