"""资源管理页面构建。"""

from __future__ import annotations

from PySide6.QtCore import QSize, Qt
from PySide6.QtWidgets import QCheckBox, QComboBox, QFrame, QHBoxLayout, QHeaderView, QLabel, QLineEdit, QListWidget, QMenu, QPushButton, QSplitter, QTreeWidget, QVBoxLayout, QWidget
from .app_widgets import PathBreadcrumb, RepositoryList, RepositoryTree


class ResourcePageMixin:
    """资源管理页面构建。"""

    def _build_resource_page(self) -> QWidget:
        resource_page = QWidget()
        self.resource_page = resource_page
        resource_layout = QVBoxLayout(resource_page)
        resource_layout.setContentsMargins(24, 20, 24, 22)
        resource_layout.setSpacing(14)
        # 保留后台状态承载控件，避免移除页面标题后打断异步任务状态链路。
        self.repo_heading = QLabel()
        self.repo_heading.setVisible(False)
        resource_heading = QHBoxLayout()
        self.view_button = QPushButton("查看 ▾")
        view_menu = QMenu(self)
        detailed_action = view_menu.addAction("详细信息模式")
        thumbnail_action = view_menu.addAction("缩略图模式")
        detailed_action.triggered.connect(lambda: self._set_view_mode("details"))
        thumbnail_action.triggered.connect(lambda: self._set_view_mode("thumbnails"))
        self.view_button.setMenu(view_menu)
        self.refresh_repos_button = QPushButton("读取 / 刷新仓库")
        self.refresh_repos_button.clicked.connect(self.load_repositories)
        resource_heading.addWidget(self.refresh_repos_button)
        self.update_index_button = QPushButton("更新索引")
        self.update_index_button.clicked.connect(self.update_all_indexes)
        resource_heading.addWidget(self.update_index_button)
        self.refresh_files_button = QPushButton("刷新目录")
        self.refresh_files_button.setEnabled(False)
        self.refresh_files_button.clicked.connect(self.load_remote_files)
        resource_heading.addWidget(self.refresh_files_button)
        resource_heading.addWidget(self.view_button)
        resource_heading.addWidget(QLabel("分组依据"))
        self.group_by_combo = QComboBox()
        self.group_by_combo.addItem("无", "")
        self.group_by_combo.addItem("名称", "name")
        self.group_by_combo.addItem("类型", "type")
        self.group_by_combo.addItem("大小", "size")
        self.group_by_combo.currentIndexChanged.connect(self._render_remote_details)
        resource_heading.addWidget(self.group_by_combo)
        self.compact_view_button = QCheckBox("紧凑视图")
        self.compact_view_button.toggled.connect(self._compact_view_changed)
        resource_heading.addWidget(self.compact_view_button)
        resource_heading.addStretch()
        self.resource_search_scope = QComboBox()
        self.resource_search_scope.addItem("全部仓库", "all")
        self.resource_search_scope.addItem("当前账户", "account")
        self.resource_search_scope.addItem("当前仓库", "repository")
        self.resource_search_scope.addItem("当前目录", "directory")
        self.resource_search_scope.setMinimumWidth(112)
        self.resource_search_scope.currentIndexChanged.connect(self._schedule_global_search)
        self.resource_search_type = QComboBox()
        self.resource_search_type.addItem("全部类型", "all")
        self.resource_search_type.addItem("视频", "video")
        self.resource_search_type.addItem("图片", "image")
        self.resource_search_type.addItem("文档", "document")
        self.resource_search_type.addItem("压缩包", "archive")
        self.resource_search_type.setMinimumWidth(100)
        self.resource_search_type.currentIndexChanged.connect(self._schedule_global_search)
        self.resource_search_tag = QComboBox()
        self.resource_search_tag.setMinimumWidth(108)
        self.resource_search_tag.currentIndexChanged.connect(self._schedule_global_search)
        self.resource_search_edit = QLineEdit()
        self.resource_search_edit.setPlaceholderText("高级搜索：路径片段 文件名前段 后段")
        self.resource_search_edit.setClearButtonEnabled(True)
        self.resource_search_edit.setMinimumWidth(220)
        self.resource_search_edit.textChanged.connect(self._schedule_global_search)
        self.resource_search_edit.returnPressed.connect(self._perform_global_search)
        self.resource_search_button = QPushButton("搜索")
        self.resource_search_button.clicked.connect(self.show_resource_search)
        self.resource_back_button = QPushButton("返回上一级")
        self.resource_back_button.setEnabled(False)
        self.resource_back_button.clicked.connect(self._go_to_parent_directory)
        resource_heading.addWidget(self.resource_back_button)
        resource_heading.addWidget(self.resource_search_button)
        resource_layout.addLayout(resource_heading)

        resource_splitter = QSplitter(Qt.Orientation.Horizontal)
        self.resource_splitter = resource_splitter
        resource_splitter.setChildrenCollapsible(False)
        resource_splitter.setHandleWidth(9)
        repo_card = QFrame(objectName="card")
        repo_card.setMinimumWidth(245)
        repo_layout = QVBoxLayout(repo_card)
        repo_layout.setContentsMargins(16, 16, 16, 16)
        repo_layout.addWidget(QLabel("仓库", objectName="section"))
        self.type_combo = QComboBox()
        self.type_combo.addItem("全部（模型 + 数据集）", "all")
        self.type_combo.addItem("模型仓库", "model")
        self.type_combo.addItem("数据集仓库", "dataset")
        self.type_combo.currentIndexChanged.connect(self._render_repositories)
        repo_layout.addWidget(self.type_combo)
        self.repo_list = QTreeWidget()
        self.repo_list.setHeaderHidden(True)
        self.repo_list.itemSelectionChanged.connect(self._repo_selected)
        self.repo_list.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.repo_list.customContextMenuRequested.connect(self._repository_context_menu)
        repo_layout.addWidget(self.repo_list, 1)
        resource_splitter.addWidget(repo_card)

        explorer_card = QFrame(objectName="card")
        explorer_layout = QVBoxLayout(explorer_card)
        explorer_layout.setContentsMargins(16, 16, 16, 16)
        explorer_toolbar = QHBoxLayout()
        self.resource_path_label = PathBreadcrumb()
        self.resource_path_label.path_selected.connect(self._go_to_directory)
        explorer_toolbar.addWidget(self.resource_path_label, 1)
        self.new_folder_button = QPushButton("新建文件夹")
        self.new_folder_button.setEnabled(False)
        self.new_folder_button.clicked.connect(self.new_folder)
        explorer_toolbar.addWidget(self.new_folder_button)
        self.download_selected_button = QPushButton("下载文件")
        self.download_selected_button.setEnabled(False)
        self.download_selected_button.clicked.connect(self._download_selected_remote)
        explorer_toolbar.addWidget(self.download_selected_button)
        self.web_manage_button = QPushButton("删除")
        self.web_manage_button.setEnabled(False)
        self.web_manage_button.clicked.connect(self._delete_selected_remote)
        explorer_toolbar.addWidget(self.web_manage_button)
        explorer_layout.addLayout(explorer_toolbar)
        self.resource_drop_hint = QLabel("将本地文件或文件夹拖到下方任意目录，即可直接上传到该目录", objectName="dropHint")
        explorer_layout.addWidget(self.resource_drop_hint)
        self.remote_tree = RepositoryTree()
        self.remote_tree.setParent(explorer_card)
        self.remote_tree.setObjectName("repositoryTree")
        self.remote_tree.setHeaderLabels(["名称", "类型", "大小", "路径"])
        remote_header = self.remote_tree.header()
        remote_header.setSectionResizeMode(QHeaderView.ResizeMode.Interactive)
        remote_header.setStretchLastSection(True)
        self.remote_tree.setColumnWidth(0, 300)
        self.remote_tree.setColumnWidth(1, 90)
        self.remote_tree.setColumnWidth(2, 100)
        self.remote_tree.setColumnWidth(3, 260)
        self.remote_tree.itemSelectionChanged.connect(self._remote_selected)
        self.remote_tree.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.remote_tree.customContextMenuRequested.connect(self._remote_context_menu)
        self.remote_tree.paths_dropped.connect(self._repository_paths_dropped)
        self.remote_tree.setVisible(False)
        self.remote_detail_tree = RepositoryTree()
        self.remote_detail_tree.setObjectName("repositoryTree")
        self.remote_detail_tree.setHeaderLabels(["名称", "类型", "大小"])
        detail_header = self.remote_detail_tree.header()
        detail_header.setSortIndicatorShown(True)
        detail_header.setSectionsClickable(True)
        detail_header.sectionClicked.connect(self._change_detail_sort)
        self.remote_detail_tree.setColumnWidth(0, 280)
        self.remote_detail_tree.setColumnWidth(1, 90)
        self.remote_detail_tree.itemSelectionChanged.connect(self._remote_detail_selected)
        self.remote_detail_tree.itemDoubleClicked.connect(self._open_remote_detail)
        self.remote_detail_tree.paths_dropped.connect(self._repository_paths_dropped)
        self.remote_detail_tree.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.remote_detail_tree.customContextMenuRequested.connect(self._remote_detail_context_menu)
        explorer_layout.addWidget(self.remote_detail_tree, 1)
        self.remote_thumbnail_list = RepositoryList()
        self.remote_thumbnail_list.setViewMode(QListWidget.ViewMode.IconMode)
        self.remote_thumbnail_list.setResizeMode(QListWidget.ResizeMode.Adjust)
        self.remote_thumbnail_list.setMovement(QListWidget.Movement.Static)
        self.remote_thumbnail_list.setWordWrap(True)
        self.remote_thumbnail_list.setIconSize(QSize(208, 117))
        self.remote_thumbnail_list.setGridSize(QSize(224, 154))
        self.remote_thumbnail_list.setSpacing(6)
        self.remote_thumbnail_list.setUniformItemSizes(True)
        self.remote_thumbnail_list.setTextElideMode(Qt.TextElideMode.ElideRight)
        self.remote_thumbnail_list.itemSelectionChanged.connect(self._remote_thumbnail_selected)
        self.remote_thumbnail_list.itemDoubleClicked.connect(self._open_remote_thumbnail)
        self.remote_thumbnail_list.paths_dropped.connect(self._repository_paths_dropped)
        self.remote_thumbnail_list.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.remote_thumbnail_list.customContextMenuRequested.connect(self._remote_thumbnail_context_menu)
        self.remote_thumbnail_list.setVisible(False)
        explorer_layout.addWidget(self.remote_thumbnail_list, 1)
        self.global_search_label = QLabel("", objectName="subtitle")
        self.global_search_label.setVisible(False)
        explorer_layout.addWidget(self.global_search_label)
        self.global_search_tree = QTreeWidget()
        self.global_search_tree.setObjectName("repositoryTree")
        self.global_search_tree.setHeaderLabels(["名称", "类型", "大小", "仓库", "路径"])
        global_header = self.global_search_tree.header()
        global_header.setSectionResizeMode(QHeaderView.ResizeMode.Interactive)
        global_header.setStretchLastSection(True)
        global_header.setSortIndicatorShown(True)
        global_header.sectionClicked.connect(self._change_global_search_sort)
        self.global_search_tree.setColumnWidth(0, 240)
        self.global_search_tree.setColumnWidth(1, 90)
        self.global_search_tree.setColumnWidth(2, 100)
        self.global_search_tree.setColumnWidth(3, 230)
        self.global_search_tree.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.global_search_tree.customContextMenuRequested.connect(self._global_search_context_menu)
        self.global_search_tree.itemDoubleClicked.connect(self._open_global_search_result)
        self.global_search_tree.setVisible(False)
        explorer_layout.addWidget(self.global_search_tree, 1)
        resource_splitter.addWidget(explorer_card)
        resource_splitter.setSizes([270, 820])
        resource_layout.addWidget(resource_splitter, 1)

        return resource_page
