"""传输队列与统计页面构建。"""

from __future__ import annotations

from PySide6.QtCore import QDateTime, Qt
from PySide6.QtWidgets import QCheckBox, QDateTimeEdit, QFrame, QGridLayout, QHBoxLayout, QHeaderView, QLabel, QLineEdit, QProgressBar, QPushButton, QTabWidget, QTableWidget, QTextEdit, QVBoxLayout, QWidget
from datetime import datetime, timedelta
from qfluentwidgets import ScrollArea as FluentScrollArea
from .app_widgets import DropArea, TransferChart


class TransferPageMixin:
    """传输队列与统计页面构建。"""

    def _build_transfer_page(self) -> QWidget:
        transfer_page = QWidget()
        transfer_layout = QVBoxLayout(transfer_page)
        transfer_layout.setContentsMargins(24, 20, 24, 22)
        transfer_layout.setSpacing(12)
        transfer_layout.addWidget(QLabel("传输列表", objectName="title"))
        self.queue_tabs = QTabWidget()
        upload_page = QWidget()
        upload_layout = QVBoxLayout(upload_page)
        upload_layout.setContentsMargins(8, 12, 8, 8)
        target_row = QHBoxLayout()
        target_row.addWidget(QLabel("上传到："))
        self.target_edit = QLineEdit()
        self.target_edit.setPlaceholderText("根目录")
        target_row.addWidget(self.target_edit, 1)
        upload_layout.addLayout(target_row)
        self.drop_area = DropArea()
        self.drop_area.paths_dropped.connect(self.add_paths)
        upload_layout.addWidget(self.drop_area)
        pick_row = QHBoxLayout()
        files_button = QPushButton("选择文件")
        files_button.clicked.connect(self.pick_files)
        folder_button = QPushButton("选择文件夹")
        folder_button.clicked.connect(self.pick_folder)
        clear_button = QPushButton("清空")
        clear_button.clicked.connect(self.clear_queue)
        pick_row.addWidget(files_button)
        pick_row.addWidget(folder_button)
        pick_row.addWidget(clear_button)
        pick_row.addStretch()
        upload_layout.addLayout(pick_row)
        self.queue_table = QTableWidget(0, 4)
        self.queue_table.setHorizontalHeaderLabels(["本地项目", "类型", "目标路径", "状态"])
        queue_header = self.queue_table.horizontalHeader()
        queue_header.setSectionResizeMode(QHeaderView.ResizeMode.Interactive)
        queue_header.setMinimumSectionSize(70)
        queue_header.setStretchLastSection(False)
        self.queue_table.setColumnWidth(0, 360)
        self.queue_table.setColumnWidth(1, 90)
        self.queue_table.setColumnWidth(2, 260)
        self.queue_table.setColumnWidth(3, 130)
        self.queue_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.queue_table.setEditTriggers(QTableWidget.EditTrigger.DoubleClicked | QTableWidget.EditTrigger.EditKeyPressed)
        upload_layout.addWidget(self.queue_table, 1)
        upload_options = QHBoxLayout()
        self.keep_folder_name = QCheckBox("保留文件夹名称")
        self.keep_folder_name.setChecked(True)
        upload_options.addWidget(self.keep_folder_name)
        upload_options.addStretch()
        self.upload_button = QPushButton("开始上传", objectName="primary")
        self.upload_button.setEnabled(False)
        self.upload_button.clicked.connect(self.start_upload)
        upload_options.addWidget(self.upload_button)
        self.pause_upload_button = QPushButton("暂停")
        self.pause_upload_button.setEnabled(False)
        self.pause_upload_button.clicked.connect(self.pause_upload)
        upload_options.addWidget(self.pause_upload_button)
        self.resume_upload_button = QPushButton("恢复")
        self.resume_upload_button.setEnabled(False)
        self.resume_upload_button.clicked.connect(self.resume_upload)
        upload_options.addWidget(self.resume_upload_button)
        self.cancel_upload_button = QPushButton("取消")
        self.cancel_upload_button.setEnabled(False)
        self.cancel_upload_button.clicked.connect(self.cancel_upload)
        upload_options.addWidget(self.cancel_upload_button)
        upload_layout.addLayout(upload_options)
        self.progress = QProgressBar()
        self.progress.setRange(0, 100)
        self.progress.setFormat("%p%")
        upload_layout.addWidget(self.progress)
        self.upload_stats = QLabel("速度：-- · 剩余：--", objectName="subtitle")
        upload_layout.addWidget(self.upload_stats)
        self.queue_tabs.addTab(upload_page, "上传")

        download_page = QWidget()
        download_layout = QVBoxLayout(download_page)
        download_layout.setContentsMargins(8, 12, 8, 8)
        download_layout.addWidget(QLabel("在资源管理页面右键文件或文件夹，可添加到此队列。", objectName="subtitle"))
        self.download_table = QTableWidget(0, 3)
        self.download_table.setHorizontalHeaderLabels(["远端资源", "本地位置", "状态"])
        download_header = self.download_table.horizontalHeader()
        download_header.setSectionResizeMode(0, QHeaderView.ResizeMode.Stretch)
        download_header.setSectionResizeMode(1, QHeaderView.ResizeMode.Stretch)
        download_header.setSectionResizeMode(2, QHeaderView.ResizeMode.Fixed)
        download_header.setMinimumSectionSize(80)
        download_header.setStretchLastSection(False)
        self.download_table.setColumnWidth(2, 180)
        self.download_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.download_table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        download_layout.addWidget(self.download_table, 1)
        download_buttons = QHBoxLayout()
        clear_download_button = QPushButton("清空")
        clear_download_button.clicked.connect(self.clear_download_queue)
        download_buttons.addWidget(clear_download_button)
        download_buttons.addStretch()
        self.download_button = QPushButton("开始下载", objectName="primary")
        self.download_button.setEnabled(False)
        self.download_button.clicked.connect(self.start_download)
        download_buttons.addWidget(self.download_button)
        self.pause_download_button = QPushButton("暂停")
        self.pause_download_button.setEnabled(False)
        self.pause_download_button.clicked.connect(self.pause_download)
        download_buttons.addWidget(self.pause_download_button)
        self.resume_download_button = QPushButton("恢复")
        self.resume_download_button.setEnabled(False)
        self.resume_download_button.clicked.connect(self.resume_download)
        download_buttons.addWidget(self.resume_download_button)
        self.stop_download_button = QPushButton("停止")
        self.stop_download_button.setEnabled(False)
        self.stop_download_button.clicked.connect(self.stop_download)
        download_buttons.addWidget(self.stop_download_button)
        download_layout.addLayout(download_buttons)
        self.download_progress = QProgressBar()
        self.download_progress.setRange(0, 100)
        self.download_progress.setFormat("%p%")
        download_layout.addWidget(self.download_progress)
        self.download_stats = QLabel("速度：-- · 剩余：--", objectName="subtitle")
        download_layout.addWidget(self.download_stats)
        self.queue_tabs.addTab(download_page, "下载")

        statistics_page = QWidget()
        statistics_page_layout = QVBoxLayout(statistics_page)
        statistics_page_layout.setContentsMargins(0, 0, 0, 0)
        statistics_scroll = FluentScrollArea()
        statistics_scroll.setObjectName("statisticsScroll")
        statistics_scroll.setWidgetResizable(True)
        statistics_scroll.setFrameShape(QFrame.Shape.NoFrame)
        statistics_content = QWidget()
        statistics_content.setObjectName("statisticsContent")
        statistics_layout = QVBoxLayout(statistics_content)
        statistics_layout.setContentsMargins(10, 14, 10, 16)
        statistics_layout.setSpacing(14)

        filter_card = QFrame(objectName="statsFilterCard")
        filter_layout = QGridLayout(filter_card)
        filter_layout.setContentsMargins(16, 14, 16, 14)
        filter_layout.setHorizontalSpacing(12)
        filter_layout.setVerticalSpacing(10)
        filter_layout.addWidget(QLabel("时间段", objectName="section"), 0, 0, 1, 4)
        filter_layout.addWidget(QLabel("开始时间", objectName="metricCaption"), 1, 0)
        self.statistics_start_edit = QDateTimeEdit()
        self.statistics_start_edit.setObjectName("statisticsDateEdit")
        self.statistics_start_edit.setCalendarPopup(True)
        self.statistics_start_edit.setDisplayFormat("yyyy-MM-dd HH:mm:ss")
        self.statistics_start_edit.setFixedWidth(136)
        self.statistics_end_edit = QDateTimeEdit()
        self.statistics_end_edit.setObjectName("statisticsDateEdit")
        self.statistics_end_edit.setCalendarPopup(True)
        self.statistics_end_edit.setDisplayFormat("yyyy-MM-dd HH:mm:ss")
        self.statistics_end_edit.setFixedWidth(136)
        now = datetime.now()
        session_start = datetime.fromtimestamp(self.session_started_at)
        self.statistics_start_edit.setDateTime(QDateTime(max(session_start, now - timedelta(days=1))))
        self.statistics_end_edit.setDateTime(QDateTime(now))
        filter_layout.addWidget(self.statistics_start_edit, 2, 0)
        filter_layout.addWidget(QLabel("结束时间", objectName="metricCaption"), 1, 1)
        filter_layout.addWidget(self.statistics_end_edit, 2, 1)
        self.statistics_live_checkbox = QCheckBox("实时")
        self.statistics_live_checkbox.setChecked(True)
        self.statistics_live_checkbox.toggled.connect(self._refresh_transfer_statistics)
        filter_layout.addWidget(self.statistics_live_checkbox, 2, 2)
        refresh_statistics_button = QPushButton("刷新")
        refresh_statistics_button.clicked.connect(self._refresh_transfer_statistics)
        filter_layout.addWidget(refresh_statistics_button, 2, 3)
        filter_layout.setColumnStretch(0, 1)
        filter_layout.setColumnStretch(1, 1)
        statistics_layout.addWidget(filter_card)

        metrics_row = QHBoxLayout()
        metrics_row.setSpacing(12)

        def add_metric(caption: str) -> QLabel:
            card = QFrame(objectName="metricCard")
            layout = QVBoxLayout(card)
            layout.setContentsMargins(14, 12, 14, 12)
            layout.setSpacing(7)
            label = QLabel(caption, objectName="metricCaption")
            value = QLabel("0 B/s", objectName="metricValue")
            value.setAlignment(Qt.AlignmentFlag.AlignCenter)
            value.setMinimumWidth(130)
            layout.addWidget(label)
            layout.addWidget(value)
            metrics_row.addWidget(card, 1)
            return value

        self.statistics_upload_value = add_metric("当前上传速度")
        self.statistics_download_value = add_metric("当前下载速度")
        self.statistics_learned_value = add_metric("已学习上传速度")
        statistics_layout.addLayout(metrics_row)

        upload_chart_card = QFrame(objectName="statsChartCard")
        upload_chart_layout = QVBoxLayout(upload_chart_card)
        upload_chart_layout.setContentsMargins(16, 14, 16, 12)
        upload_chart_layout.setSpacing(10)
        upload_chart_header = QHBoxLayout()
        upload_chart_header.addWidget(QLabel("上传速度", objectName="section"))
        upload_chart_header.addStretch()
        self.upload_chart_metrics = QLabel("平均 0 B/s  ·  峰值 0 B/s", objectName="speedPill")
        upload_chart_header.addWidget(self.upload_chart_metrics)
        upload_chart_layout.addLayout(upload_chart_header)
        self.upload_chart = TransferChart("upload", "#1677ff")
        upload_chart_layout.addWidget(self.upload_chart)
        statistics_layout.addWidget(upload_chart_card)

        download_chart_card = QFrame(objectName="statsChartCard")
        download_chart_layout = QVBoxLayout(download_chart_card)
        download_chart_layout.setContentsMargins(16, 14, 16, 12)
        download_chart_layout.setSpacing(10)
        download_chart_header = QHBoxLayout()
        download_chart_header.addWidget(QLabel("下载速度", objectName="section"))
        download_chart_header.addStretch()
        self.download_chart_metrics = QLabel("平均 0 B/s  ·  峰值 0 B/s", objectName="speedPill")
        download_chart_header.addWidget(self.download_chart_metrics)
        download_chart_layout.addLayout(download_chart_header)
        self.download_chart = TransferChart("download", "#16a34a")
        download_chart_layout.addWidget(self.download_chart)
        statistics_layout.addWidget(download_chart_card)

        self.statistics_summary = QLabel(objectName="transferTotalPill")
        self.statistics_summary.setMinimumWidth(520)
        self.statistics_summary.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.statistics_summary.setWordWrap(False)
        statistics_layout.addWidget(self.statistics_summary)
        self.statistics_note = QLabel("仅统计本次软件启动以来的数据；速度每秒采样。", objectName="subtitle")
        self.statistics_note.setWordWrap(True)
        statistics_layout.addWidget(self.statistics_note)
        statistics_scroll.setWidget(statistics_content)
        statistics_page_layout.addWidget(statistics_scroll)
        self.queue_tabs.addTab(statistics_page, "统计分析")
        transfer_layout.addWidget(self.queue_tabs, 1)
        self.log = QTextEdit()
        self.log.setReadOnly(True)
        self.log.setMaximumHeight(110)
        self.log.setPlaceholderText("传输记录会显示在这里")
        transfer_layout.addWidget(self.log)

        return transfer_page
