"""图床与 AVIF 配置页面构建。"""

from __future__ import annotations

from PySide6.QtWidgets import QAbstractItemView, QCheckBox, QComboBox, QFrame, QGridLayout, QHBoxLayout, QHeaderView, QLabel, QLineEdit, QPushButton, QSpinBox, QTableWidget, QVBoxLayout, QWidget
from .app_widgets import DropArea
from .avif_converter import find_ffmpeg


class ImageBedPageMixin:
    """图床与 AVIF 配置页面构建。"""

    def _build_image_page(self) -> QWidget:
        image_page = QWidget()
        self.image_page = image_page
        image_layout = QVBoxLayout(image_page)
        image_layout.setContentsMargins(24, 20, 24, 22)
        image_layout.setSpacing(14)
        image_layout.addWidget(QLabel("图床", objectName="title"))
        image_layout.addWidget(QLabel(
            "拖入图片或按 Ctrl+V 上传到指定仓库，生成直链并保存本地缓存。",
            objectName="subtitle",
        ))
        image_config = QFrame(objectName="card")
        image_config_layout = QHBoxLayout(image_config)
        image_config_layout.setContentsMargins(16, 14, 16, 14)
        image_config_layout.addWidget(QLabel("账户"))
        self.image_account_combo = QComboBox()
        self.image_account_combo.currentIndexChanged.connect(self._render_image_repository_options)
        self.image_account_combo.currentIndexChanged.connect(self._save_image_settings)
        image_config_layout.addWidget(self.image_account_combo)
        image_config_layout.addWidget(QLabel("仓库"))
        self.image_repo_combo = QComboBox()
        self.image_repo_combo.currentIndexChanged.connect(self._save_image_settings)
        image_config_layout.addWidget(self.image_repo_combo, 1)
        image_config_layout.addWidget(QLabel("存储路径"))
        self.image_dest_edit = QLineEdit()
        self.image_dest_edit.setPlaceholderText("images")
        self.image_dest_edit.setText("images")
        self.image_dest_edit.editingFinished.connect(self._save_image_settings)
        image_config_layout.addWidget(self.image_dest_edit, 1)
        image_layout.addWidget(image_config)
        self.image_drop_area = DropArea("将图片拖到这里上传", "也可按 Ctrl+V；上传前会验证文件确实是图片")
        self.image_drop_area.paths_dropped.connect(self._upload_images)
        image_layout.addWidget(self.image_drop_area)
        image_actions = QHBoxLayout()
        image_pick = QPushButton("选择图片")
        image_pick.clicked.connect(self._pick_images)
        image_actions.addWidget(image_pick)
        self.image_auto_avif = QCheckBox("自动转换为 AVIF")
        self.image_auto_avif.toggled.connect(self._save_image_settings)
        image_actions.addWidget(self.image_auto_avif)
        self.avif_config_button = QPushButton("AVIF 详细配置")
        self.avif_config_button.setCheckable(True)
        image_actions.addWidget(self.avif_config_button)
        image_actions.addStretch()
        image_copy = QPushButton("复制所选直链")
        image_copy.clicked.connect(self._copy_selected_image_link)
        image_actions.addWidget(image_copy)
        image_open = QPushButton("缓存打开")
        image_open.clicked.connect(self._open_selected_image)
        image_actions.addWidget(image_open)
        image_remove = QPushButton("移除记录")
        image_remove.clicked.connect(self._remove_selected_image)
        image_actions.addWidget(image_remove)
        image_layout.addLayout(image_actions)
        self.avif_config_card = QFrame(objectName="card")
        avif_grid = QGridLayout(self.avif_config_card)
        avif_grid.setContentsMargins(16, 14, 16, 14)
        avif_grid.setHorizontalSpacing(12)
        avif_grid.setVerticalSpacing(10)
        avif_grid.addWidget(QLabel("质量（AWJ 默认 70）"), 0, 0)
        self.avif_quality = QSpinBox()
        self.avif_quality.setRange(1, 100)
        self.avif_quality.setValue(70)
        self.avif_quality.valueChanged.connect(self._save_image_settings)
        avif_grid.addWidget(self._stepper(self.avif_quality), 0, 1)
        avif_grid.addWidget(QLabel("速度（AWJ 默认 5）"), 0, 2)
        self.avif_speed = QSpinBox()
        self.avif_speed.setRange(0, 10)
        self.avif_speed.setValue(5)
        self.avif_speed.valueChanged.connect(self._save_image_settings)
        avif_grid.addWidget(self._stepper(self.avif_speed), 0, 3)
        avif_grid.addWidget(QLabel("色度采样"), 1, 0)
        self.avif_chroma = QComboBox()
        for label, value in (("自动（4:2:0）", "auto"), ("4:4:4", "444"), ("4:2:2", "422"), ("4:2:0", "420")):
            self.avif_chroma.addItem(label, value)
        self.avif_chroma.currentIndexChanged.connect(self._save_image_settings)
        avif_grid.addWidget(self.avif_chroma, 1, 1)
        avif_grid.addWidget(QLabel("位深"), 1, 2)
        self.avif_bit_depth = QComboBox()
        for label, value in (("自动（10-bit）", "auto"), ("8-bit", "8"), ("10-bit", "10"), ("12-bit", "12")):
            self.avif_bit_depth.addItem(label, value)
        self.avif_bit_depth.currentIndexChanged.connect(self._save_image_settings)
        avif_grid.addWidget(self.avif_bit_depth, 1, 3)
        self.avif_keep_metadata = QCheckBox("保留可兼容的图片元数据")
        self.avif_keep_metadata.setChecked(True)
        self.avif_keep_metadata.toggled.connect(self._save_image_settings)
        avif_grid.addWidget(self.avif_keep_metadata, 2, 0, 1, 2)
        ffmpeg_path = find_ffmpeg()
        self.avif_tool_status = QLabel(
            f"FFmpeg：{ffmpeg_path}" if ffmpeg_path else "FFmpeg：未找到（可放入 embedded-tools/ffmpeg/ffmpeg.exe）",
            objectName="subtitle",
        )
        self.avif_tool_status.setWordWrap(True)
        avif_grid.addWidget(self.avif_tool_status, 2, 2, 1, 2)
        self.avif_config_card.setVisible(False)
        self.avif_config_button.toggled.connect(self.avif_config_card.setVisible)
        image_layout.addWidget(self.avif_config_card)
        self.image_table = QTableWidget(0, 6)
        self.image_table.setHorizontalHeaderLabels(["文件", "仓库", "远端路径", "直链", "缓存", "上传时间"])
        self.image_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Interactive)
        self.image_table.horizontalHeader().setStretchLastSection(True)
        self.image_table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.image_table.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self.image_table.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.image_table.setColumnWidth(0, 180)
        self.image_table.setColumnWidth(1, 200)
        self.image_table.setColumnWidth(2, 260)
        self.image_table.setColumnWidth(3, 280)
        self.image_table.doubleClicked.connect(self._open_selected_image)
        image_layout.addWidget(self.image_table, 1)
        self.image_status_label = QLabel("等待上传图片", objectName="subtitle")
        image_layout.addWidget(self.image_status_label)
        return image_page
