"""设置页面构建。"""

from __future__ import annotations

from PySide6.QtCore import Qt
from PySide6.QtWidgets import QAbstractItemView, QCheckBox, QComboBox, QDoubleSpinBox, QFrame, QGridLayout, QHBoxLayout, QHeaderView, QLabel, QLineEdit, QPushButton, QSpinBox, QTableWidget, QVBoxLayout, QWidget
from qfluentwidgets import FluentIcon as FIF, ScrollArea as FluentScrollArea, SettingCardGroup, SpinBox as FluentSpinBox, ToolButton
from . import __version__
from .fluent_ui import CleanComboBox, ControlSettingCard, FluentSwitchButton, PanelSettingCard


class SettingsPageMixin:
    """设置页面构建。"""

    def _build_settings_page(self) -> QWidget:
        settings_page = QWidget()
        self.settings_page = settings_page
        settings_page_layout = QVBoxLayout(settings_page)
        settings_page_layout.setContentsMargins(0, 0, 0, 0)
        settings_scroll = FluentScrollArea()
        settings_scroll.setObjectName("settingsScroll")
        settings_scroll.setWidgetResizable(True)
        settings_scroll.setFrameShape(QFrame.Shape.NoFrame)
        settings_content = QWidget()
        settings_content.setObjectName("settingsContent")
        settings_layout = QVBoxLayout(settings_content)
        settings_layout.setContentsMargins(28, 24, 28, 28)
        settings_layout.setSpacing(18)
        settings_layout.addWidget(QLabel("设置", objectName="title"))
        settings_notice_row = QHBoxLayout()
        self.disable_settings_wheel = FluentSwitchButton()
        self.disable_settings_wheel.setChecked(True)
        self.disable_settings_wheel.toggled.connect(self._wheel_setting_changed)
        settings_notice_row.addWidget(self.disable_settings_wheel)
        settings_notice_row.addWidget(QLabel("本页内容自动保存", objectName="subtitle"))
        settings_notice_row.addStretch()
        token_card = QFrame(objectName="card")
        token_layout = QVBoxLayout(token_card)
        token_layout.setContentsMargins(20, 18, 20, 20)
        token_layout.addWidget(QLabel("账号设置 · ModelScope 账户", objectName="panelTitle"))
        token_heading = QHBoxLayout()
        self.token_heading_label = QLabel("Token 登录", objectName="section")
        token_heading.addWidget(self.token_heading_label, 0, Qt.AlignmentFlag.AlignTop)
        token_heading.addStretch()
        self.add_account_button = ToolButton(FIF.ADD)
        self.add_account_button.setFixedSize(38, 36)
        self.add_account_button.setToolTip("添加账户")
        self.add_account_button.clicked.connect(self.add_account)
        token_heading.addWidget(self.add_account_button, 0, Qt.AlignmentFlag.AlignTop)
        self.remove_account_button = ToolButton(FIF.REMOVE)
        self.remove_account_button.setFixedSize(38, 36)
        self.remove_account_button.setToolTip("移除所选账户")
        self.remove_account_button.clicked.connect(self.remove_account)
        token_heading.addWidget(self.remove_account_button, 0, Qt.AlignmentFlag.AlignTop)
        token_layout.addLayout(token_heading)
        token_layout.addWidget(QLabel("Token 使用设备绑定加密；添加后会自动验证并取得用户名。", objectName="subtitle"))
        self.account_table = QTableWidget(0, 5)
        self.account_table.setHorizontalHeaderLabels(["账户名称", "用户名", "Token", "安全记住", "状态"])
        self.account_table.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.account_table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.account_table.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self.account_table.verticalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Fixed)
        self.account_table.verticalHeader().setDefaultSectionSize(42)
        self.account_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Interactive)
        self.account_table.horizontalHeader().setStretchLastSection(True)
        self.account_table.setColumnWidth(0, 160)
        self.account_table.setColumnWidth(1, 150)
        self.account_table.setColumnWidth(2, 190)
        self.account_table.setColumnWidth(3, 90)
        self.account_table.setMaximumHeight(190)
        self.account_table.itemSelectionChanged.connect(self._account_selected)
        token_layout.addWidget(self.account_table)
        self.account_name_edit = QLineEdit()
        self.account_name_edit.setPlaceholderText("账户名称（可选）")
        token_layout.addWidget(self.account_name_edit)
        self.token_edit = QLineEdit()
        self.token_edit.setEchoMode(QLineEdit.EchoMode.Password)
        self.token_edit.setPlaceholderText("输入 ModelScope Access Token")
        self.token_edit.returnPressed.connect(self.connect_account)
        token_layout.addWidget(self.token_edit)
        token_options = QHBoxLayout()
        self.show_token = QCheckBox("显示")
        self.show_token.toggled.connect(lambda checked: self.token_edit.setEchoMode(QLineEdit.EchoMode.Normal if checked else QLineEdit.EchoMode.Password))
        self.remember_token = QCheckBox("安全记住")
        self.remember_token.setChecked(True)
        token_options.addWidget(self.show_token)
        token_options.addWidget(self.remember_token)
        token_options.addStretch()
        token_layout.addLayout(token_options)
        self.connect_button = QPushButton("保存并验证账户", objectName="primary")
        self.connect_button.clicked.connect(self.connect_account)
        token_layout.addWidget(self.connect_button, alignment=Qt.AlignmentFlag.AlignLeft)
        self.account_label = QLabel("尚未连接", objectName="subtitle")
        token_layout.addWidget(self.account_label)
        token_layout.addSpacing(12)
        self.online_separator = QFrame()
        self.online_separator.setFrameShape(QFrame.Shape.HLine)
        token_layout.addWidget(self.online_separator)
        online_heading = QHBoxLayout()
        online_heading.addWidget(QLabel("ModelScope 账户 在线登录", objectName="section"))
        online_heading.addStretch()
        add_web_account_button = ToolButton(FIF.ADD)
        add_web_account_button.setFixedSize(38, 36)
        add_web_account_button.setToolTip("添加网页登录账户")
        add_web_account_button.clicked.connect(self.add_web_account)
        online_heading.addWidget(add_web_account_button)
        remove_web_account_button = ToolButton(FIF.REMOVE)
        remove_web_account_button.setFixedSize(38, 36)
        remove_web_account_button.setToolTip("移除所选网页登录账户")
        remove_web_account_button.clicked.connect(self.remove_web_account)
        online_heading.addWidget(remove_web_account_button)
        token_layout.addLayout(online_heading)
        token_layout.addWidget(QLabel(
            "网页登录账户独立保存；密码和短信验证码仅输入 ModelScope 官方页面。",
            objectName="subtitle",
        ))
        self.web_account_table = QTableWidget(0, 4)
        self.web_account_table.setHorizontalHeaderLabels(["账户名称", "用户名", "状态", "操作"])
        self.web_account_table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.web_account_table.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self.web_account_table.verticalHeader().setDefaultSectionSize(42)
        self.web_account_table.horizontalHeader().setStretchLastSection(True)
        self.web_account_table.setColumnWidth(0, 190)
        self.web_account_table.setColumnWidth(1, 160)
        self.web_account_table.setColumnWidth(2, 90)
        self.web_account_table.setMaximumHeight(190)
        self.web_account_table.itemChanged.connect(self._web_account_item_changed)
        token_layout.addWidget(self.web_account_table)

        download_card = QFrame(objectName="card")
        download_setting_layout = QVBoxLayout(download_card)
        download_setting_layout.setContentsMargins(20, 18, 20, 20)
        download_setting_layout.setSpacing(14)
        download_setting_layout.addWidget(QLabel("下载设置", objectName="panelTitle"))
        download_setting_layout.addWidget(QLabel("默认下载路径", objectName="subtitle"))
        download_path_row = QHBoxLayout()
        self.download_path_edit = QLineEdit()
        self.download_path_edit.setReadOnly(True)
        download_path_row.addWidget(self.download_path_edit, 1)
        change_download_button = QPushButton("修改")
        change_download_button.clicked.connect(self.change_download_path)
        download_path_row.addWidget(change_download_button)
        download_setting_layout.addLayout(download_path_row)
        drop_threshold_row = QHBoxLayout()
        drop_threshold_row.addWidget(QLabel("拖放上传阈值", objectName="subtitle"))
        self.drop_upload_threshold_mb = QSpinBox()
        self.drop_upload_threshold_mb.setRange(1, 1024 * 1024)
        self.drop_upload_threshold_mb.setValue(1024)
        self.drop_upload_threshold_mb.setSuffix(" MB")
        self.drop_upload_threshold_mb.valueChanged.connect(self._drop_upload_threshold_changed)
        drop_threshold_row.addWidget(self._stepper(self.drop_upload_threshold_mb), 1)
        download_setting_layout.addLayout(drop_threshold_row)
        upload_queue_row = QHBoxLayout()
        upload_queue_row.addWidget(QLabel("上传队列数", objectName="subtitle"))
        self.upload_queue_count = QSpinBox()
        self.upload_queue_count.setRange(1, 16)
        self.upload_queue_count.setValue(4)
        self.upload_queue_count.setToolTip("ModelScope Python SDK 同时上传的文件任务数")
        self.upload_queue_count.valueChanged.connect(self._upload_queue_count_changed)
        upload_queue_row.addWidget(self._stepper(self.upload_queue_count), 1)
        download_setting_layout.addLayout(upload_queue_row)

        player_card = QFrame(objectName="card")
        player_layout = QVBoxLayout(player_card)
        player_layout.setContentsMargins(20, 18, 20, 20)
        player_layout.addWidget(QLabel("播放设置", objectName="panelTitle"))
        self.builtin_player_enabled = FluentSwitchButton("使用本地 PotPlayer 作为默认视频/图片播放器")
        self.builtin_player_enabled.setChecked(True)
        self.builtin_player_enabled.toggled.connect(self._builtin_player_setting_changed)
        player_layout.addWidget(self.builtin_player_enabled)
        player_layout.addWidget(QLabel(
            "播放器不随程序预装。点击下载后将使用内置 aria2-next 获取并校验 PotPlayer.7z，再通过 7z-zstd 解压到本地。",
            objectName="subtitle",
        ))
        player_install_row = QHBoxLayout()
        self.potplayer_install_button = QPushButton("下载并安装 PotPlayer", objectName="primary")
        self.potplayer_install_button.clicked.connect(self.install_potplayer_from_modelscope)
        player_install_row.addWidget(self.potplayer_install_button)
        self.potplayer_folder_button = QPushButton("打开播放器目录")
        self.potplayer_folder_button.clicked.connect(self.open_potplayer_folder)
        player_install_row.addWidget(self.potplayer_folder_button)
        player_install_row.addStretch()
        player_layout.addLayout(player_install_row)
        self.builtin_player_status = QLabel("PotPlayer：正在检查", objectName="subtitle")
        player_layout.addWidget(self.builtin_player_status)
        player_heading = QHBoxLayout()
        self.player_heading_label = QLabel("第三方播放器", objectName="section")
        player_heading.addWidget(self.player_heading_label, 0, Qt.AlignmentFlag.AlignTop)
        player_heading.addStretch()
        self.add_player_button = ToolButton(FIF.ADD)
        self.add_player_button.setFixedSize(38, 36)
        self.add_player_button.setToolTip("添加播放器")
        self.add_player_button.clicked.connect(self.add_external_player)
        player_heading.addWidget(self.add_player_button, 0, Qt.AlignmentFlag.AlignTop)
        self.remove_player_button = ToolButton(FIF.REMOVE)
        self.remove_player_button.setFixedSize(38, 36)
        self.remove_player_button.setToolTip("删除所选播放器")
        self.remove_player_button.clicked.connect(self.remove_external_player)
        player_heading.addWidget(self.remove_player_button, 0, Qt.AlignmentFlag.AlignTop)
        player_layout.addLayout(player_heading)
        player_layout.addWidget(QLabel("媒体右键菜单会在本地 PotPlayer 之后显示以下第三方播放器。", objectName="subtitle"))
        self.player_table = QTableWidget(0, 2)
        self.player_table.setHorizontalHeaderLabels(["播放器名称", "程序路径"])
        self.player_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Interactive)
        self.player_table.horizontalHeader().setStretchLastSection(True)
        self.player_table.setColumnWidth(0, 180)
        self.player_table.setMaximumHeight(150)
        self.player_table.itemChanged.connect(self._players_edited)
        player_layout.addWidget(self.player_table)

        aria_card = QFrame(objectName="card")
        aria_layout = QVBoxLayout(aria_card)
        aria_layout.setContentsMargins(20, 18, 20, 20)
        aria_layout.setSpacing(14)
        aria_layout.addWidget(QLabel("aria2-next 详细配置", objectName="section"))
        aria_layout.addWidget(QLabel("按文件大小自动分配 HTTP 连接和下载分段，并为小文件仓库增加并行任务。", objectName="subtitle"))
        self.aria_strategy_combo = CleanComboBox()
        self.aria_strategy_combo.addItem("自动（按文件大小，推荐）", userData="adaptive")
        aria_layout.addWidget(self.aria_strategy_combo)
        aria_grid = QGridLayout()
        aria_grid.setHorizontalSpacing(12)
        aria_grid.setVerticalSpacing(14)
        aria_grid.addWidget(QLabel("文件类别"), 0, 0)
        aria_grid.addWidget(QLabel("大小阈值"), 0, 1)
        aria_grid.addWidget(QLabel("HTTP 连接 / 分段数"), 0, 2)
        aria_grid.addWidget(QLabel("小文件"), 1, 0)
        self.aria_small_limit = QDoubleSpinBox()
        self.aria_small_limit.setRange(0.01, 102400.0)
        self.aria_small_limit.setDecimals(2)
        self.aria_small_limit.setSuffix(" MB 以下")
        self.aria_small_limit.setValue(1.0)
        aria_grid.addWidget(self._stepper(self.aria_small_limit), 1, 1)
        self.aria_small_segments = QSpinBox()
        self.aria_small_segments.setRange(1, 128)
        self.aria_small_segments.setValue(1)
        aria_grid.addWidget(self._stepper(self.aria_small_segments), 1, 2)
        aria_grid.addWidget(QLabel("中等文件"), 2, 0)
        aria_grid.addWidget(QLabel("介于小文件和大文件之间", objectName="subtitle"), 2, 1)
        self.aria_medium_segments = QSpinBox()
        self.aria_medium_segments.setRange(1, 128)
        self.aria_medium_segments.setValue(32)
        aria_grid.addWidget(self._stepper(self.aria_medium_segments), 2, 2)
        aria_grid.addWidget(QLabel("大文件"), 3, 0)
        self.aria_large_limit = QDoubleSpinBox()
        self.aria_large_limit.setRange(0.02, 1024000.0)
        self.aria_large_limit.setDecimals(2)
        self.aria_large_limit.setSuffix(" MB 以上")
        self.aria_large_limit.setValue(100.0)
        aria_grid.addWidget(self._stepper(self.aria_large_limit), 3, 1)
        self.aria_large_segments = QSpinBox()
        self.aria_large_segments.setRange(1, 128)
        self.aria_large_segments.setValue(64)
        aria_grid.addWidget(self._stepper(self.aria_large_segments), 3, 2)
        aria_layout.addLayout(aria_grid)
        aria_note = QLabel("提示：aria2-next 的最小分片为 1 MB；分段数是上限，较小文件会按实际大小使用可用分片。", objectName="subtitle")
        aria_note.setWordWrap(True)
        aria_layout.addWidget(aria_note)
        reset_aria_button = QPushButton("重置 aria2-next 配置到默认值")
        reset_aria_button.clicked.connect(self.reset_aria2_settings)
        aria_layout.addWidget(reset_aria_button, alignment=Qt.AlignmentFlag.AlignLeft)
        for control in (
            self.aria_small_limit,
            self.aria_small_segments,
            self.aria_medium_segments,
            self.aria_large_limit,
            self.aria_large_segments,
        ):
            control.valueChanged.connect(self._save_aria2_settings)

        aria_layout.addWidget(QLabel("上传 / 下载限速", objectName="section"))
        aria_layout.addWidget(QLabel(
            "0 表示不限速。分时时段按每天重复执行，跨越午夜的时段同样有效；多条重叠时以最后一条为准。",
            objectName="subtitle",
        ))
        self.speed_limit_enabled = FluentSwitchButton("启用传输限速")
        self.speed_limit_enabled.toggled.connect(self._save_transfer_policy)
        aria_layout.addWidget(self.speed_limit_enabled)
        base_limit_row = QHBoxLayout()
        base_limit_row.addWidget(QLabel("默认上传"))
        self.base_upload_limit = QDoubleSpinBox()
        self.base_upload_limit.setRange(0, 102400)
        self.base_upload_limit.setDecimals(2)
        self.base_upload_limit.setSuffix(" MB/s")
        self.base_upload_limit.valueChanged.connect(self._save_transfer_policy)
        base_limit_row.addWidget(self._stepper(self.base_upload_limit))
        base_limit_row.addWidget(QLabel("默认下载"))
        self.base_download_limit = QDoubleSpinBox()
        self.base_download_limit.setRange(0, 102400)
        self.base_download_limit.setDecimals(2)
        self.base_download_limit.setSuffix(" MB/s")
        self.base_download_limit.valueChanged.connect(self._save_transfer_policy)
        base_limit_row.addWidget(self._stepper(self.base_download_limit))
        base_limit_row.addStretch()
        aria_layout.addLayout(base_limit_row)
        self.speed_rule_table = QTableWidget(0, 4)
        self.speed_rule_table.setHorizontalHeaderLabels(["开始时间", "结束时间", "上传 MB/s", "下载 MB/s"])
        self.speed_rule_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.speed_rule_table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.speed_rule_table.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self.speed_rule_table.setMaximumHeight(190)
        aria_layout.addWidget(self.speed_rule_table)
        speed_rule_actions = QHBoxLayout()
        add_speed_rule = QPushButton("＋ 添加分时时段")
        add_speed_rule.clicked.connect(lambda: self._add_speed_rule())
        speed_rule_actions.addWidget(add_speed_rule)
        remove_speed_rule = QPushButton("－ 删除所选时段")
        remove_speed_rule.clicked.connect(self._remove_speed_rule)
        speed_rule_actions.addWidget(remove_speed_rule)
        reset_speed_limits = QPushButton("重置限速配置")
        reset_speed_limits.clicked.connect(self._reset_transfer_policy)
        speed_rule_actions.addWidget(reset_speed_limits)
        speed_rule_actions.addStretch()
        aria_layout.addLayout(speed_rule_actions)
        self.speed_limit_status = QLabel("当前：上传不限速 · 下载不限速", objectName="subtitle")
        aria_layout.addWidget(self.speed_limit_status)

        general_card = QFrame(objectName="card")
        general_layout = QVBoxLayout(general_card)
        general_layout.setContentsMargins(20, 18, 20, 20)
        general_layout.addWidget(QLabel("基本设置", objectName="section"))
        general_grid = QGridLayout()
        general_grid.addWidget(QLabel("语言"), 0, 0)
        self.language_combo = CleanComboBox()
        self.language_combo.addItem("简体中文", userData="zh_CN")
        self.language_combo.addItem("English", userData="en_US")
        self.language_combo.currentIndexChanged.connect(self._language_changed)
        general_grid.addWidget(self.language_combo, 0, 1)
        general_grid.addWidget(QLabel("关闭窗口时"), 1, 0)
        self.close_behavior_combo = CleanComboBox()
        self.close_behavior_combo.addItem("第一次询问", userData="ask")
        self.close_behavior_combo.addItem("最小化到通知区域", userData="tray")
        self.close_behavior_combo.addItem("直接关闭程序", userData="close")
        self.close_behavior_combo.currentIndexChanged.connect(self._close_behavior_changed)
        general_grid.addWidget(self.close_behavior_combo, 1, 1)
        self.startup_checkbox = FluentSwitchButton()
        self.startup_checkbox.toggled.connect(self._startup_changed)
        general_grid.addWidget(self.startup_checkbox, 2, 1)
        general_layout.addLayout(general_grid)

        update_card = QFrame(objectName="card")
        update_layout = QVBoxLayout(update_card)
        update_layout.setContentsMargins(20, 18, 20, 20)
        update_layout.addWidget(QLabel("软件更新", objectName="panelTitle"))
        self.auto_update_checkbox = FluentSwitchButton("启动后自动检查更新")
        self.auto_update_checkbox.setChecked(True)
        self.auto_update_checkbox.toggled.connect(self._auto_update_changed)
        update_layout.addWidget(self.auto_update_checkbox)
        update_actions = QHBoxLayout()
        self.update_status_label = QLabel(f"当前版本：{__version__}", objectName="subtitle")
        self.update_status_label.setWordWrap(True)
        update_actions.addWidget(self.update_status_label, 1)
        self.update_check_button = QPushButton("手动检查更新")
        self.update_check_button.clicked.connect(self.check_for_updates)
        update_actions.addWidget(self.update_check_button)
        self.update_restart_button = QPushButton("立即重启更新", objectName="primary")
        self.update_restart_button.clicked.connect(self.restart_to_install_update)
        self.update_restart_button.hide()
        update_actions.addWidget(self.update_restart_button)
        update_layout.addLayout(update_actions)

        theme_card = QFrame(objectName="card")
        theme_layout = QVBoxLayout(theme_card)
        theme_layout.setContentsMargins(20, 18, 20, 20)
        theme_layout.addWidget(QLabel("主题设置", objectName="section"))
        self.gpu_acceleration_checkbox = FluentSwitchButton()
        self.gpu_acceleration_checkbox.toggled.connect(self._graphics_settings_changed)
        theme_layout.addWidget(self.gpu_acceleration_checkbox)
        self.acrylic_checkbox = FluentSwitchButton()
        self.acrylic_checkbox.toggled.connect(self._graphics_settings_changed)
        theme_layout.addWidget(self.acrylic_checkbox)
        theme_row = QHBoxLayout()
        theme_row.addWidget(QLabel("颜色主题"))
        self.theme_combo = CleanComboBox()
        self.theme_combo.addItem("跟随系统", userData="system")
        self.theme_combo.addItem("浅色", userData="light")
        self.theme_combo.addItem("深色", userData="dark")
        self.theme_combo.currentIndexChanged.connect(self._theme_changed)
        theme_row.addWidget(self.theme_combo)
        theme_row.addStretch()
        theme_layout.addLayout(theme_row)
        self.font_size_spin = FluentSpinBox()
        self.font_size_spin.setRange(9, 18)
        self.font_size_spin.setValue(10)
        self.font_size_spin.setSuffix(" pt")
        self.font_size_spin.valueChanged.connect(self._font_size_changed)
        self.graphics_status = QLabel("亚克力效果由 Windows GPU 合成器处理。", objectName="subtitle")
        theme_layout.addWidget(self.graphics_status)

        index_card = QFrame(objectName="card")
        index_layout = QVBoxLayout(index_card)
        index_layout.setContentsMargins(20, 18, 20, 20)
        index_layout.addWidget(QLabel("索引和预览", objectName="panelTitle"))
        index_layout.addWidget(QLabel("索引更新", objectName="section"))
        index_layout.addWidget(QLabel(
            "启动时完整更新一次；日常修改会等到空闲或程序进入后台后再更新。",
            objectName="subtitle",
        ))
        index_row = QHBoxLayout()
        index_row.addWidget(QLabel("后台索引间隔"))
        self.background_index_minutes = QSpinBox()
        self.background_index_minutes.setRange(1, 1440)
        self.background_index_minutes.setValue(5)
        self.background_index_minutes.setSuffix(" 分钟")
        self.background_index_minutes.valueChanged.connect(self._background_index_interval_changed)
        index_row.addWidget(self._stepper(self.background_index_minutes))
        index_row.addStretch()
        index_layout.addLayout(index_row)

        preview_card = QFrame(objectName="card")
        preview_layout = QVBoxLayout(preview_card)
        preview_layout.setContentsMargins(20, 18, 20, 20)
        preview_layout.addWidget(QLabel("预览", objectName="section"))
        preview_layout.addWidget(QLabel("当前目录优先生成；大目录和子目录会在用户空闲时分批递归处理。原图仅短暂驻留内存。", objectName="subtitle"))
        preview_row = QHBoxLayout()
        preview_row.addWidget(QLabel("自动对大小小于"))
        self.thumbnail_maximum_mb = QDoubleSpinBox()
        self.thumbnail_maximum_mb.setRange(0.1, 10240)
        self.thumbnail_maximum_mb.setDecimals(1)
        self.thumbnail_maximum_mb.setValue(100.0)
        self.thumbnail_maximum_mb.setSuffix(" MB 的图片生成缩略图")
        self.thumbnail_maximum_mb.valueChanged.connect(self._save_preview_settings)
        preview_row.addWidget(self._stepper(self.thumbnail_maximum_mb))
        preview_row.addStretch()
        preview_layout.addLayout(preview_row)
        thumbnail_workers_row = QHBoxLayout()
        thumbnail_workers_row.addWidget(QLabel("缩略图生成线程数"))
        self.thumbnail_workers = QSpinBox()
        self.thumbnail_workers.setRange(1, 128)
        self.thumbnail_workers.setValue(16)
        self.thumbnail_workers.valueChanged.connect(self._save_preview_settings)
        thumbnail_workers_row.addWidget(self._stepper(self.thumbnail_workers))
        thumbnail_workers_row.addStretch()
        preview_layout.addLayout(thumbnail_workers_row)
        copy_row = QHBoxLayout()
        copy_row.addWidget(QLabel("复制阈值"))
        self.copy_threshold_value = QDoubleSpinBox()
        self.copy_threshold_value.setRange(0.1, 10240)
        self.copy_threshold_value.setDecimals(1)
        self.copy_threshold_value.setValue(100.0)
        self.copy_threshold_value.valueChanged.connect(self._save_preview_settings)
        copy_row.addWidget(self._stepper(self.copy_threshold_value))
        self.copy_threshold_unit = CleanComboBox()
        self.copy_threshold_unit.addItem("MB", userData=1024 ** 2)
        self.copy_threshold_unit.addItem("GB", userData=1024 ** 3)
        self.copy_threshold_unit.currentIndexChanged.connect(self._save_preview_settings)
        copy_row.addWidget(self.copy_threshold_unit)
        copy_row.addStretch()
        preview_layout.addLayout(copy_row)

        resource_card = QFrame(objectName="card")
        resource_layout = QVBoxLayout(resource_card)
        resource_layout.setContentsMargins(20, 18, 20, 20)
        resource_layout.addWidget(QLabel("进程资源监控", objectName="panelTitle"))
        self.resource_usage_label = QLabel("CPU：-- · 内存：-- · 私有内存：-- · 显存：--", objectName="pathPill")
        self.resource_usage_label.setWordWrap(True)
        resource_layout.addWidget(self.resource_usage_label)
        resource_layout.addWidget(QLabel(
            "每 2 秒采样本进程；显存使用 Windows GPU 性能计数器，驱动不支持时显示不可用。",
            objectName="subtitle",
        ))
        resource_controls = QHBoxLayout()
        self.auto_memory_release = FluentSwitchButton("进入后台后自动释放内存")
        self.auto_memory_release.setChecked(True)
        self.auto_memory_release.toggled.connect(self._resource_settings_changed)
        resource_controls.addWidget(self.auto_memory_release)
        resource_controls.addWidget(QLabel("触发阈值"))
        self.memory_release_threshold = QSpinBox()
        self.memory_release_threshold.setRange(128, 32768)
        self.memory_release_threshold.setValue(512)
        self.memory_release_threshold.setSuffix(" MB")
        self.memory_release_threshold.valueChanged.connect(self._resource_settings_changed)
        resource_controls.addWidget(self._stepper(self.memory_release_threshold))
        resource_controls.addStretch()
        release_memory_button = QPushButton("立即释放内存")
        release_memory_button.clicked.connect(self._release_process_memory)
        resource_controls.addWidget(release_memory_button)
        resource_layout.addLayout(resource_controls)

        alist_card = QFrame(objectName="card")
        alist_layout = QVBoxLayout(alist_card)
        alist_layout.setContentsMargins(20, 18, 20, 20)
        alist_layout.addWidget(QLabel("WebDAV 设置", objectName="section"))
        alist_layout.addWidget(QLabel("AList V3 挂载", objectName="section"))
        alist_warning = QLabel("使用 WebDAV 网关。受到 ModelScope 官方 API 限制，不支持删除、重命名、移动和复制操作。", objectName="subtitle")
        alist_warning.setWordWrap(True)
        alist_layout.addWidget(alist_warning)
        alist_grid = QGridLayout()
        alist_grid.addWidget(QLabel("配置方式"), 0, 0)
        self.alist_protocol_combo = CleanComboBox()
        self.alist_protocol_combo.addItem("WebDAV", userData="webdav")
        alist_grid.addWidget(self.alist_protocol_combo, 0, 1)
        alist_grid.addWidget(QLabel("监听范围"), 1, 0)
        self.alist_host_combo = CleanComboBox()
        self.alist_host_combo.addItem("仅本机（127.0.0.1）", userData="127.0.0.1")
        self.alist_host_combo.addItem("局域网 / Docker（0.0.0.0）", userData="0.0.0.0")
        alist_grid.addWidget(self.alist_host_combo, 1, 1)
        self.alist_port_label = QLabel("端口")
        alist_grid.addWidget(self.alist_port_label, 2, 0)
        self.alist_port = QSpinBox()
        self.alist_port.setRange(1024, 65535)
        self.alist_port.setValue(9867)
        self.alist_port_control = self._stepper(self.alist_port)
        alist_grid.addWidget(self.alist_port_control, 2, 1)
        alist_grid.addWidget(QLabel("用户名"), 3, 0)
        self.alist_username = QLineEdit("modelscope")
        alist_grid.addWidget(self.alist_username, 3, 1)
        alist_grid.addWidget(QLabel("密码"), 4, 0)
        self.alist_password = QLineEdit()
        self.alist_password.setEchoMode(QLineEdit.EchoMode.Password)
        alist_grid.addWidget(self.alist_password, 4, 1)
        self.alist_show_password = QCheckBox("显示密码")
        self.alist_show_password.toggled.connect(
            lambda checked: self.alist_password.setEchoMode(
                QLineEdit.EchoMode.Normal if checked else QLineEdit.EchoMode.Password
            )
        )
        alist_grid.addWidget(self.alist_show_password, 5, 1)
        alist_layout.addLayout(alist_grid)
        self.alist_url_label = QLabel("WebDAV 地址：--", objectName="pathPill")
        self.alist_url_label.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)
        alist_layout.addWidget(self.alist_url_label)
        alist_help = QLabel("AList 后台添加存储：驱动选择 WebDAV，厂商选择“其他”，地址填写上方 URL；挂载全部内容时根文件夹路径填写 / 或留空，只挂载子目录时可填写 /models、/datasets 或 /public。若 AList 在 Docker 中，可使用 host.docker.internal。其他设备连接时必须选择“局域网 / Docker”监听；若仍然连接超时，请在 Windows Defender 防火墙中允许本程序。", objectName="subtitle")
        alist_help.setWordWrap(True)
        alist_layout.addWidget(alist_help)
        alist_actions = QHBoxLayout()
        self.alist_auto_start = FluentSwitchButton("启动程序后自动启动监听")
        self.alist_auto_start.toggled.connect(self._save_alist_settings)
        alist_actions.addWidget(self.alist_auto_start)
        alist_actions.addStretch()
        self.alist_start_button = QPushButton("启动")
        self.alist_start_button.clicked.connect(self.apply_alist_settings)
        alist_actions.addWidget(self.alist_start_button)
        self.alist_stop_button = QPushButton("停止")
        self.alist_stop_button.clicked.connect(self.stop_alist)
        alist_actions.addWidget(self.alist_stop_button)
        alist_layout.addLayout(alist_actions)
        self.alist_status = QLabel("未启动", objectName="subtitle")
        alist_layout.addWidget(self.alist_status)
        for control in (self.alist_host_combo, self.alist_port, self.alist_username, self.alist_password):
            if isinstance(control, (QComboBox, CleanComboBox)):
                control.currentIndexChanged.connect(self._update_alist_url)
                control.currentIndexChanged.connect(self._save_alist_settings)
            elif isinstance(control, QSpinBox):
                control.valueChanged.connect(self._update_alist_url)
                control.valueChanged.connect(self._save_alist_settings)
            else:
                control.textChanged.connect(self._update_alist_url)
                control.textChanged.connect(self._save_alist_settings)
        aria_card.setObjectName("")
        aria_layout.setContentsMargins(0, 16, 0, 0)
        download_setting_layout.addWidget(aria_card)
        preview_card.setObjectName("")
        preview_layout.setContentsMargins(0, 16, 0, 0)
        index_layout.addWidget(preview_card)
        basic_group = SettingCardGroup("基本设置", settings_content)
        basic_group.addSettingCards((
            ControlSettingCard(FIF.LANGUAGE, "语言", "修改后立即应用，无需重启", self.language_combo, trailing_margin=40),
            ControlSettingCard(FIF.CLOSE, "关闭窗口时", "选择询问、最小化到通知区域或直接退出", self.close_behavior_combo, trailing_margin=40),
            ControlSettingCard(FIF.POWER_BUTTON, "开机自启", "登录 Windows 后自动启动 ModelScope Manager", self.startup_checkbox, trailing_margin=40),
            ControlSettingCard(FIF.SCROLL, "滚轮保护", "避免滚动设置页时意外修改数值", self.disable_settings_wheel, trailing_margin=40),
        ))

        appearance_group = SettingCardGroup("个性化", settings_content)
        appearance_group.addSettingCards((
            ControlSettingCard(FIF.PALETTE, "应用主题", "跟随系统，或固定使用浅色/深色主题", self.theme_combo, trailing_margin=40),
            ControlSettingCard(FIF.FONT_SIZE, "全局字号", "同步缩放 Qt、Fluent 控件和 Matplotlib", self.font_size_spin, trailing_margin=40),
            ControlSettingCard(FIF.SPEED_HIGH, "GPU 加速", "桌面 OpenGL 设置在下次启动后生效", self.gpu_acceleration_checkbox, trailing_margin=40),
            ControlSettingCard(FIF.TRANSPARENT, "Blur 亚克力", "由 Windows 桌面合成器渲染半透明背景", self.acrylic_checkbox, trailing_margin=40),
            ControlSettingCard(FIF.INFO, "渲染状态", "当前窗口合成与背景策略", self.graphics_status, trailing_margin=40),
        ))

        panel_specs = (
            ("软件更新", FIF.UPDATE, "ModelScope 更新", "从 ARXChem/Software-List 获取最新便携包", update_card),
            ("账号设置", FIF.PEOPLE, "ModelScope 账户", "Token 与网页登录信息使用设备绑定加密保存", token_card),
            ("下载设置", FIF.DOWNLOAD, "下载与传输", "默认目录、aria2-next 分段、SDK 上传队列和共享限速", download_card),
            ("播放设置", FIF.PLAY, "媒体播放器", "内置 PotPlayer 与第三方播放器", player_card),
            ("索引和预览", FIF.SEARCH, "索引与预览", "后台索引、缩略图和复制阈值", index_card),
            ("资源监控", FIF.SPEED_HIGH, "CPU、内存与显存", "本进程实时占用与后台自动内存回收", resource_card),
        )
        settings_layout.addWidget(basic_group)
        settings_layout.addWidget(appearance_group)
        for group_title, icon, title, description, panel in panel_specs:
            for label in panel.findChildren(QLabel, options=Qt.FindChildOption.FindDirectChildrenOnly):
                if label.objectName() == "panelTitle":
                    label.hide()
                    break
            group = SettingCardGroup(group_title, settings_content)
            group.addSettingCard(PanelSettingCard(icon, title, description, panel, group))
            settings_layout.addWidget(group)
        self.alist_port_label.hide()
        webdav_group = SettingCardGroup("WebDAV 设置", settings_content)
        webdav_group.addSettingCards((
            ControlSettingCard(
                FIF.CONNECT, "监听端口", "端口冲突时会自动寻找相邻可用端口并立即保存",
                self.alist_port_control, webdav_group,
            ),
            PanelSettingCard(
                FIF.GLOBE, "WebDAV 网关", "监听范围、账户凭据与启动状态",
                alist_card, webdav_group,
            ),
        ))
        settings_layout.insertWidget(settings_layout.count() - 1, webdav_group)

        experimental_panel = QFrame()
        experimental_layout = QVBoxLayout(experimental_panel)
        experimental_layout.setContentsMargins(18, 14, 18, 14)
        experimental_layout.setSpacing(12)
        experimental_layout.addWidget(QLabel(
            "这些选项会降低凭据安全性或绕过稳定性保护。凭据类选项启用前必须完成风险确认和四位数加法验证。",
            objectName="subtitle",
        ))
        self.plaintext_credentials_switch = FluentSwitchButton("明文保存密码、Token 与登录 Cookie")
        self.disable_device_destruction_switch = FluentSwitchButton("关闭跨设备凭据自动销毁")
        for control in (
            self.plaintext_credentials_switch,
            self.disable_device_destruction_switch,
        ):
            experimental_layout.addWidget(control)
        self.plaintext_credentials_switch.toggled.connect(
            lambda checked: self._experimental_setting_toggled(
                "plaintext_credentials", self.plaintext_credentials_switch, checked, True,
            )
        )
        self.disable_device_destruction_switch.toggled.connect(
            lambda checked: self._experimental_setting_toggled(
                "disable_device_destruction", self.disable_device_destruction_switch, checked, True,
            )
        )
        experimental_group = SettingCardGroup("实验性功能", settings_content)
        experimental_group.addSettingCard(PanelSettingCard(
            FIF.DEVELOPER_TOOLS,
            "高风险测试选项",
            "明文凭据与跨设备保留",
            experimental_panel,
            experimental_group,
        ))
        settings_layout.addWidget(experimental_group)
        settings_layout.addStretch()
        settings_scroll.setWidget(settings_content)
        settings_page_layout.addWidget(settings_scroll)

        return settings_page
